---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-app-dep
  labels:
    app: vpro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpro-app
  template:
    metadata:
      labels:
        app: vpro-app
    spec:
      containers:
      - name: vpro-app
        image: haarish1999/vproapp:latest
        ports:
        - containerPort: 8080
          name: vpro-app-port
      initContainers:
      - name: init-mydb
        image: busybox
        args: ['-c', 'until nslookup vpro-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        args: ['-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
