---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-db-dep
  labels:
    app: vpro-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpro-db
  template:
    metadata:
      labels:
        app: vpro-db
    spec:
      containers:
      - name: vpro-db
        image: haarish1999/vprodb:latest
        volumeMounts:
        - name: vpro-db-vol
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: vpro-db-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valuefrom:
            secretKeyRef:
              name: vprofile-secret
              key: db-pass
      volumes:
      - name: vpro-db-vol
        persistentVolumeClaim:
          claimName: vpro-db-pvc
      initcontainers:
      - name: init-mysqldb
        image: busybox
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: vpro-db-vol
          mountPath: /var/lib/mysql
