---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpro-rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpro-rmq
  template:
    metadata:
      labels:
        app: vpro-rmq
    spec:
      containers:
      - name: vpro-rmq
        image: rabbitmq
        ports:
        - containerPort: 5672
          name: vpro-rmq-port
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valuefrom:
            secretKeyRef:
              name: vpro-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
